// Generated by CoffeeScript 1.7.1
Trill.Animation = (function() {
  function Animation() {}

  Animation.prototype.create = function() {};

  Animation.prototype.onPacketReceived = function() {};

  Animation.prototype.destroy = function() {};

  return Animation;

})();

//# sourceMappingURL=animation.map
