// Generated by CoffeeScript 1.7.1
Trill.SessionBasedGameState = (function() {
  function SessionBasedGameState() {}

  return SessionBasedGameState;

})();

//# sourceMappingURL=sessionBasedGameState.map
