// Generated by CoffeeScript 1.7.1
var connectionCache, deploy, fs, http, mime, path, send404, sendFile, serveStatic, server, sio, staticPageCache, trillServer;

fs = require('fs');

http = require('http');

sio = require('socket.io');

path = require('path');

mime = require('mime');

connectionCache = {};

staticPageCache = {};

deploy = "./deploy";

server = http.createServer(function(request, response) {
  var filePath;
  filePath = false;
  if (request.url === '/') {
    filePath = "./" + deploy + "/index.html";
  } else {
    filePath = "./" + deploy + "/" + request.url;
  }
  console.log("Sending " + filePath + " to the client...");
  return serveStatic(response, staticPageCache, filePath);
});

serveStatic = function(response, cache, absPath) {
  if (cache[absPath]) {
    return sendFile(response, absPath, cache[absPath]);
  } else {
    return fs.exists(absPath, function(exists) {
      if (exists) {
        return fs.readFile(absPath, function(err, data) {
          if (err) {
            return send404(response);
          } else {
            cache[absPath] = data;
            return sendFile(response, absPath, data);
          }
        });
      } else {
        return send404(response);
      }
    });
  }
};

server.listen(8080, "0.0.0.0", function() {
  return console.log("Received new connection");
});

sendFile = function(response, filePath, fileContents) {
  response.writeHead(200, {
    "Content-type": mime.lookup(path.basename(filePath))
  });
  return response.end(fileContents);
};

send404 = function(response) {
  response.writeHead(404, {
    'Content-Type': 'text/plain'
  });
  response.write('Error 404: resource not found');
  return response.end();
};

trillServer = require('./trill-server');

trillServer.listen(server);

//# sourceMappingURL=server.map
